Metadata writer, reader; Default number of buckets and replicas
ChesleyTan/geowave pull request #15
Opened 2019-03-19 00:29 UTC by foolhb

2019-03-19 01:01 UTC, foolhb commented
I think the metadata writer and reader are working now. There are errors in metadata deleter because nonexistent keys need to be set Util.Empty_key.

2019-03-19 02:57 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(KuduWriter.class);
This should be `KuduMetadataReader.class`

2019-03-19 03:02 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +        if (query.hasSecondaryId()) {
We can probably combine the two checks for `query.hasSecondaryId()`. We can change this to:
```
if (query.hasPrimaryId()) {
  // create primaryPred and add to scanner builder
}
if (query.hasSecondaryId()) {
  // create secondaryPred and add to scanner builder
}
scanner = scannerBuilder.build();

2019-03-19 03:03 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +      LOGGER.error("Encountered error while reading row", e);
Should probably close the scanner if not null here

2019-03-19 03:05 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataWriter.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(KuduWriter.class);
Should be `KuduMetadataWriter.class`

2019-03-19 03:08 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataWriter.java
> +          row.getVisibility() == null ? KuduUtils.EMPTY_KEY : row.getTimestamp());
Should be `row.getVisibility()`

2019-03-19 03:40 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +      LOGGER.error("Encountered error while reading row", e);
Actually, that could trigger `KuduException`, so this might be fine?

2019-03-19 03:44 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduOperations.java
> +        if (!indexExists(tableName)) {
It might be clearer to call `metadataExists()` instead of `indexExists()` here.

2019-03-19 03:48 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataWriter.java
> +  public KuduMetadataWriter(KuduOperations operations, String tableName) {
`CassandraMetadataWriter` passes in the table name, but I think we should pass in `MetadataType` instead, for both consistency with the reader/deleter and for safety (to ensure that the table name is valid). Seems like both accumulo and hbase implementations do this

2019-03-19 03:50 UTC, ChesleyTan commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/util/KuduUtils.java
> +  public static final byte[] EMPTY_KEY = new byte[] {0};
Could we combine this with `EMPTY_PARTITION_KEY` (replace `EMPTY_PARTITION_KEY` with `EMPTY_KEY`)?

2019-03-19 04:28 UTC, dannyqiu commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +      KuduScanner scanner;
Can you move this to when you actually initialize the scanner?

2019-03-19 04:28 UTC, dannyqiu commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataWriter.java
> +
nit: extra newline?

2019-03-19 04:37 UTC, ChesleyTan commented
> I think the metadata writer and reader are working now. There are errors in metadata deleter but I'm not sure if this needs fixing since these errors are probably caused by my silly metadata table schema definition ...

I think the error is because we don't specify the secondary ID key when deleting the rows (since the secondary ID and the timestamp are part of the primary key, we need to specify them in the PartialRow). This is something we'll have to fix.

2019-03-22 16:03 UTC, dannyqiu requested changes

2019-03-22 16:03 UTC, dannyqiu commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +import org.apache.kudu.client.*;
Expand wildcard

2019-03-22 16:03 UTC, dannyqiu commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataReader.java
> +import java.util.*;
Expand wildcard

2019-03-22 16:03 UTC, dannyqiu commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataWriter.java
> +    } catch (KuduException e) {
Don't need to catch kuduexception

2019-03-22 16:03 UTC, dannyqiu commented on extensions/datastores/kudu/src/main/java/org/locationtech/geowave/datastore/kudu/operations/KuduMetadataWriter.java
> +      partialRow.addBinary(KuduMetadataField.GW_PRIMARY_ID_KEY.getFieldName(), row.getPrimaryId());
Use populaterow from metadatarow

2019-03-22 16:16 UTC, dannyqiu submitted a review, later dismissed
Lgtm

2019-03-23 04:49 UTC, ChesleyTan approved these changes

2019-03-23 05:03 UTC, merged